#ifndef __KMS_HTTP_END_POINT_ACTION_H__
#define __KMS_HTTP_END_POINT_ACTION_H__

G_BEGIN_DECLS
typedef enum
{
  KMS_HTTP_END_POINT_ACTION_GET,
  KMS_HTTP_END_POINT_ACTION_POST,
  KMS_HTTP_END_POINT_ACTION_UNDEFINED
} KmsHttpEndPointAction;

G_END_DECLS
#endif /* __KMS_HTTP_END_POINT_ACTION_H__ */
